import { StyleDefine } from '@easy-coder/sdk/style'

export const editorStyleModels: (keyof StyleDefine)[] = [
  'alignItems',
  'background',
  'filter',
  'position',
  'borderColor',
  'borderRadius',
  'borderStyle',
  'borderWidth',
  'boxShadow',
  'boxSizing',
  'display',
  'flexDirection',
  'gap',
  'gridAutoFlow',
  'gridGap',
  'gridTemplate',
  'height',
  'width',
  'justifyContent',
  'margin',
  'maxHeight',
  'maxWidth',
  'minHeight',
  'minWidth',
  'outline',
  'overflow',
  'padding',
  'transform',
  'transition',
  'opacity',
  'zIndex',
]
