export const local = {
  passwordIsDiff: {
    zh: '两次密码不一致',
    en: 'Passwords Do Not Match',
    ja: 'パスワードが一致しない',
    af: 'twee wagwoorde stem nie ooreen nie',
    ar: 'كلمتا المرور غير متطابقتين',
    be: 'паролі не супадаюць',
    bg: 'паролите не съвпадат',
    bn: 'দুটি পাসওয়ার্ড মেলে না',
    ca: 'les dues contrasenyes no coincideixen',
    cs: 'hesla se neshodují',
    cy: "nid yw'r cyfrineiriau yn cyd-fynd",
    da: 'adgangskoder er ikke ens',
    de: 'Passwörter stimmen nicht überein',
    el: 'οι κωδικοί πρόσβασης δεν ταιριάζουν',
    eo: 'pasvortoj ne kongruas',
    es: 'las contraseñas no coinciden',
    et: 'paroolid ei kattu',
    fa: 'رمزهای عبور مطابقت ندارند',
    fi: 'salasanat eivät täsmää',
    fr: 'les deux mots de passe ne correspondent pas',
    ga: 'níl an dá phasfhocal comhionann',
    gl: 'as dúas contrasinais non coinciden',
    gu: 'બે પાસવર્ડ મેળ ખાતા નથી',
    he: 'סיסמאות לא תואמות',
    hi: 'पासवर्ड मेल नहीं खाते',
    hr: 'lozinke se ne podudaraju',
    ht: 'modpas yo pa matche',
    hu: 'a két jelszó nem egyezik',
    id: 'dua kata sandi tidak cocok',
    is: 'tvö lykilorð passa ekki',
    it: 'le due password non corrispondono',
    ka: 'პაროლები არ ემთხვევა',
    kn: 'ಪಾಸ್ವರ್ಡ್ಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ',
    ko: '비밀번호 불일치',
    lt: 'slaptažodžiai nesutampa',
    lv: 'divas reizes ievadītās paroles nesakrīt',
    mk: 'двете лозинки не се совпаѓаат',
    mr: 'दोन वेळा प्रविष्ट केलेल्या पासवर्ड जुळत नाहीत',
    ms: 'kata laluan dua kali tidak sepadan',
    mt: 'il-passwordijiet mhumiex l-istess',
    nl: 'wachtwoorden komen niet overeen',
    no: 'to passord er ikke like',
    pl: 'dwa hasła nie są takie same',
    pt: 'as duas senhas não coincidem',
    ro: 'cele două parole nu coincid',
    ru: 'пароли не совпадают',
    sk: 'heslá sa nezhodujú',
    sl: 'gesli se ne ujemajo',
    sq: 'fjalëkalimet nuk përputhen',
    sv: 'Lösenorden matchar inte',
    sw: 'Nenosiri hazifanani',
    ta: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    te: 'పాస్వర్డ్లు సరిపోలడం లేదు',
    th: 'รหัสผ่านไม่ตรงกัน',
    tl: 'Hindi pareho ang mga password',
    tr: 'Şifreler uyuşmuyor',
    uk: 'Паролі не співпадають',
    ur: 'پاس ورڈز مماثل نہیں ہیں',
    vi: 'Mật khẩu không khớp',
  },
  account: {
    zh: '账号',
    en: 'Account',
    ja: 'アカウント',
    af: 'Rekening',
    ar: 'الحساب',
    be: 'уліковы запіс',
    bg: 'акаунт',
    bn: 'অ্যাকাউন্ট',
    ca: 'Compte',
    cs: 'Účet',
    cy: 'Cyfrif',
    da: 'Konto',
    de: 'Konto',
    el: 'Λογαριασμός',
    eo: 'Konto',
    es: 'Cuenta',
    et: 'Konto',
    fa: 'حساب کاربری',
    fi: 'Tunnus',
    fr: 'Compte',
    ga: 'Cuntas',
    gl: 'Conta',
    gu: 'એકાઉન્ટ',
    he: 'שם משתמש',
    hi: 'यूज़रनेम',
    hr: 'Korisničko ime',
    ht: 'Non itilizatè',
    hu: 'Fiók',
    id: 'Akun',
    is: 'Reikningur',
    it: 'Account',
    ka: 'ანგარიში',
    kn: 'ಖಾತೆ',
    ko: '계정',
    lt: 'Paskyra',
    lv: 'konts',
    mk: 'сметка',
    mr: 'खाते',
    ms: 'akaun',
    mt: 'kont',
    nl: 'account',
    no: 'Konto',
    pl: 'Konto',
    pt: 'Conta',
    ro: 'Cont',
    ru: 'Аккаунт',
    sk: 'Účet',
    sl: 'Račun',
    sq: 'Llogaria',
    sv: 'konto',
    sw: 'akaunti',
    ta: 'கணக்கு',
    te: 'ఖాతా',
    th: 'บัญชี',
    tl: 'account',
    tr: 'hesap',
    uk: 'обліковий запис',
    ur: 'اکاؤنٹ',
    vi: 'tài khoản',
  },
  nickName: {
    zh: '昵称',
    en: 'Nickname',
    ja: 'ニックネーム',
    af: 'Bynaam',
    ar: 'اللقب',
    be: 'Нікнэйм',
    bg: 'Прякор',
    bn: 'ডাকনাম',
    ca: 'Sobrenom',
    cs: 'Přezdívka',
    cy: 'Llysenw',
    da: 'Kaldenavn',
    de: 'Spitzname',
    el: 'Ψευδώνυμο',
    eo: 'Kromnomo',
    es: 'apodo',
    et: 'hüüdnimi',
    fa: 'نام مستعار',
    fi: 'lempinimi',
    fr: 'pseudo',
    ga: 'leasainm',
    gl: 'alcume',
    gu: 'ઉપનામ',
    he: 'כינוי',
    hi: 'उपनाम',
    hr: 'Nadimak',
    ht: 'Ti non',
    hu: 'Becenév',
    id: 'Nama panggilan',
    is: 'Gælunafn',
    it: 'Soprannome',
    ka: 'მეტსახელი',
    kn: 'ಅಡ್ಡಹೆಸರು',
    ko: '닉네임',
    lt: 'Slapyvardis',
    lv: 'Segvārds',
    mk: 'Прекар',
    mr: 'टोपणनाव',
    ms: 'Nama samaran',
    mt: "L-isem ta' l-utent",
    nl: 'Bijnaam',
    no: 'Kallenavn',
    pl: 'Pseudonim',
    pt: 'Apelido',
    ro: 'Poreclă',
    ru: 'Никнейм',
    sk: 'Prezývka',
    sl: 'Vzdevek',
    sq: 'Pseudonim',
    sv: 'Smeknamn',
    sw: 'Jina la utani',
    ta: 'புனைப்பெயர்',
    te: 'మారుపేరు',
    th: 'ชื่อเล่น',
    tl: 'palayaw',
    tr: 'takma ad',
    uk: 'нікнейм',
    ur: 'عرفی نام',
    vi: 'biệt danh',
  },
  email: {
    zh: '邮箱',
    en: 'Email',
    ja: 'メール',
    af: 'E-pos',
    ar: 'البريد الإلكتروني',
    be: 'пошта',
    bg: 'имейл',
    bn: 'ইমেইল',
    ca: 'Correu electrònic',
    cs: 'E-mail',
    cy: 'E-bost',
    da: 'E-mail',
    de: 'E-Mail',
    el: 'Ηλεκτρονικό ταχυδρομείο',
    eo: 'Retpoŝto',
    es: 'Correo electrónico',
    et: 'E-post',
    fa: 'ایمیل',
    fi: 'Sähköposti',
    fr: 'Email',
    ga: 'Ríomhphost',
    gl: 'Correo electrónico',
    gu: 'ઇમેઇલ',
    he: 'אימייל',
    hi: 'ईमेल',
    hr: 'Email',
    ht: 'Imèl',
    hu: 'E-mail',
    id: 'Email',
    is: 'Tölvupóstur',
    it: 'Email',
    ka: 'ელ.ფოსტა',
    kn: 'ಇಮೇಲ್',
    ko: '이메일',
    lt: 'El. paštas',
    lv: 'E-pasts',
    mk: 'Е-пошта',
    mr: 'ईमेल',
    ms: 'E-mel',
    mt: 'Email',
    nl: 'E-mail',
    no: 'E-post',
    pl: 'Poczta',
    pt: 'E-mail',
    ro: 'E-mail',
    ru: 'Почта',
    sk: 'E-mail',
    sl: 'E-pošta',
    sq: 'Email',
    sv: 'E-post',
    sw: 'Barua pepe',
    ta: 'மின்னஞ்சல்',
    te: 'ఇమెయిల్',
    th: 'อีเมล',
    tl: 'Email',
    tr: 'E-posta',
    uk: 'Електронна пошта',
    ur: 'ای میل',
    vi: 'Email',
  },
  phone: {
    zh: '电话',
    en: 'Phone',
    ja: '電話',
    af: 'Telefoon',
    ar: 'الهاتف',
    be: 'тэлефон',
    bg: 'телефон',
    bn: 'ফোন',
    ca: 'Telèfon',
    cs: 'Telefon',
    cy: 'Ffôn',
    da: 'Telefon',
    de: 'Telefon',
    el: 'Τηλέφωνο',
    eo: 'Telefono',
    es: 'Teléfono',
    et: 'Telefon',
    fa: 'تلفن',
    fi: 'Puhelin',
    fr: 'Téléphone',
    ga: 'Guthán',
    gl: 'Teléfono',
    gu: 'ફોન',
    he: 'טלפון',
    hi: 'फोन',
    hr: 'Telefon',
    ht: 'Telefòn',
    hu: 'Telefon',
    id: 'Telepon',
    is: 'Sími',
    it: 'Telefono',
    ka: 'ტელეფონი',
    kn: 'ಫೋನ್',
    ko: '전화',
    lt: 'Telefonas',
    lv: 'Telefons',
    mk: 'Телефон',
    mr: 'फोन',
    ms: 'Telefon',
    mt: 'Telefon',
    nl: 'Telefoon',
    no: 'Telefon',
    pl: 'Telefon',
    pt: 'Telefone',
    ro: 'Telefon',
    ru: 'Телефон',
    sk: 'Telefón',
    sl: 'Telefon',
    sq: 'Telefon',
    sv: 'telefon',
    sw: 'simu',
    ta: 'தொலைபேசி',
    te: 'ఫోన్',
    th: 'โทรศัพท์',
    tl: 'telepono',
    tr: 'telefon',
    uk: 'телефон',
    ur: 'فون',
    vi: 'điện thoại',
  },
  avatar: {
    zh: '头像',
    en: 'Avatar',
    ja: 'アバター',
    af: 'Profiel prentjie',
    ar: 'صورة الملف الشخصي',
    be: 'Аватар',
    bg: 'Аватар',
    bn: 'প্রোফাইল ছবি',
    ca: 'Imatge de perfil',
    cs: 'Profilový obrázek',
    cy: 'Delwedd proffil',
    da: 'Profilbillede',
    de: 'Profilbild',
    el: 'Εικόνα προφίλ',
    eo: 'Profilbildo',
    es: 'avatar',
    et: 'avatar',
    fa: 'آواتار',
    fi: 'avatar',
    fr: 'avatar',
    ga: 'avatar',
    gl: 'avatar',
    gu: 'અવતાર',
    he: 'תמונת פרופיל',
    hi: 'प्रोफाइल चित्र',
    hr: 'profilna slika',
    ht: 'pwofil imaj',
    hu: 'profilkép',
    id: 'foto profil',
    is: 'prófílmynd',
    it: 'immagine del profilo',
    ka: 'ავატარი',
    kn: 'ಪ್ರೊಫೈಲ್ ಚಿತ್ರ',
    ko: '프로필 사진',
    lt: 'profilio nuotrauka',
    lv: 'Profila bilde',
    mk: 'Профилна слика',
    mr: 'प्रोफाइल चित्र',
    ms: 'Gambar profil',
    mt: 'Avatar',
    nl: 'Avatar',
    no: 'profilbilde',
    pl: 'awatar',
    pt: 'avatar',
    ro: 'avatar',
    ru: 'аватар',
    sk: 'avatar',
    sl: 'avatar',
    sq: 'avatar',
    sv: 'Profilbild',
    sw: 'Picha ya wasifu',
    ta: 'சுயவிவர படம்',
    te: 'ప్రొఫైల్ చిత్రం',
    th: 'รูปโปรไฟล์',
    tl: 'Avatar',
    tr: 'Avatar',
    uk: 'Аватар',
    ur: 'اوتار',
    vi: 'Ảnh đại diện',
  },
  password: {
    zh: '密码',
    en: 'Password',
    ja: 'パスワード',
    af: 'Wagwoord',
    ar: 'كلمة المرور',
    be: 'Пароль',
    bg: 'Парола',
    bn: 'পাসওয়ার্ড',
    ca: 'Contrasenya',
    cs: 'Heslo',
    cy: 'Cyfrinair',
    da: 'Adgangskode',
    de: 'Passwort',
    el: 'Κωδικός πρόσβασης',
    eo: 'Pasvorto',
    es: 'Contraseña',
    et: 'Parool',
    fa: 'رمز عبور',
    fi: 'Salasana',
    fr: 'Mot de passe',
    ga: 'Pasfhocal',
    gl: 'Contrasinal',
    gu: 'પાસવર્ડ',
    he: 'סיסמה',
    hi: 'पासवर्ड',
    hr: 'Lozinka',
    ht: 'Modpas',
    hu: 'jelszó',
    id: 'kata sandi',
    is: 'lykilorð',
    it: 'password',
    ka: 'პაროლი',
    kn: 'ಪಾಸ್ವರ್ಡ್',
    ko: '비밀번호',
    lt: 'Slaptažodis',
    lv: 'Parole',
    mk: 'Лозинка',
    mr: 'पासवर्ड',
    ms: 'Kata laluan',
    mt: 'Password',
    nl: 'Wachtwoord',
    no: 'Passord',
    pl: 'Hasło',
    pt: 'Senha',
    ro: 'Parolă',
    ru: 'Пароль',
    sk: 'Heslo',
    sl: 'Geslo',
    sq: 'Fjalëkalimi',
    sv: 'Lösenord',
    sw: 'Nenosiri',
    ta: 'கடவுச்சொல்',
    te: 'పాస్వర్డ్',
    th: 'รหัสผ่าน',
    tl: 'Password',
    tr: 'Şifre',
    uk: 'Пароль',
    ur: 'پاس ورڈ',
    vi: 'Mật khẩu',
  },
  confirmPassword: {
    zh: '确认密码',
    en: 'Confirm Password',
    ja: 'パスワードを確認',
    af: 'Bevestig wagwoord',
    ar: 'تأكيد كلمة المرور',
    be: 'пацвердзіць пароль',
    bg: 'потвърждение на парола',
    bn: 'পাসওয়ার্ড নিশ্চিত করুন',
    ca: 'Confirma contrasenya',
    cs: 'Potvrdit heslo',
    cy: 'Cadarnhau cyfrinair',
    da: 'bekræft adgangskode',
    de: 'Passwort bestätigen',
    el: 'επιβεβαίωση κωδικού πρόσβασης',
    eo: 'konfirmi pasvorton',
    es: 'confirmar contraseña',
    et: 'kinnita parool',
    fa: 'تایید رمز عبور',
    fi: 'vahvista salasana',
    fr: 'confirmer le mot de passe',
    ga: 'deimhnigh an focal faire',
    gl: 'confirmar contrasinal',
    gu: 'પાસવર્ડ ખાતરી કરો',
    he: 'אישור סיסמה',
    hi: 'पासवर्ड की पुष्टि',
    hr: 'potvrdi lozinku',
    ht: 'konfime modpas',
    hu: 'jelszó megerősítése',
    id: 'konfirmasi kata sandi',
    is: 'staðfesting lykilorðs',
    it: 'conferma password',
    ka: 'პაროლის დადასტურება',
    kn: 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    ko: '비밀번호 확인',
    lt: 'patvirtinti slaptažodį',
    lv: 'Apstipriniet paroli',
    mk: 'Потврди ја лозинката',
    mr: 'पासवर्ड निश्चित करा',
    ms: 'Sahkan kata laluan',
    mt: 'Ikkonferma l-password',
    nl: 'Bevestig wachtwoord',
    no: 'Bekreft passord',
    pl: 'Potwierdź hasło',
    pt: 'Confirmar senha',
    ro: 'Confirmă parola',
    ru: 'Подтвердите пароль',
    sk: 'Potvrďte heslo',
    sl: 'Potrdite geslo',
    sq: 'Konfirmoni fjalëkalimin',
    sv: 'Bekräfta lösenord',
    sw: 'Thibitisha neno la siri',
    ta: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    te: 'పాస్వర్డ్ని నిర్ధారించండి',
    th: 'ยืนยันรหัสผ่าน',
    tl: 'Kumpirmahin ang Password',
    tr: 'Şifreyi Onayla',
    uk: 'Підтвердити пароль',
    ur: 'پاس ورڈ کی تصدیق کریں',
    vi: 'Xác nhận mật khẩu',
  },
  submit: {
    zh: '提交',
    en: 'Submit',
    ja: '提出',
    af: 'Indien',
    ar: 'إرسال',
    be: 'Адпраўка',
    bg: 'Изпращане',
    bn: 'জমা দিন',
    ca: 'Enviar',
    cs: 'Odeslat',
    cy: 'Cyflwyno',
    da: 'Indsend',
    de: 'Einreichen',
    el: 'Υποβολή',
    eo: 'Sendi',
    es: 'Enviar',
    et: 'Esita',
    fa: 'ارسال',
    fi: 'Lähetä',
    fr: 'Soumettre',
    ga: 'Cuir isteach',
    gl: 'Enviar',
    gu: 'સબમિટ કરો',
    he: 'שליחה',
    hi: 'सबमिट करें',
    hr: 'Pošalji',
    ht: 'Soumèt',
    hu: 'beküldés',
    id: 'kirim',
    is: 'senda inn',
    it: 'invia',
    ka: 'წარდგენა',
    kn: 'ಸಲ್ಲಿಸು',
    ko: '제출',
    lt: 'Pateikti',
    lv: 'Iesniegt',
    mk: 'Поднеси',
    mr: 'सबमिट करा',
    ms: 'Hantar',
    mt: 'issottomett',
    nl: 'indienen',
    no: 'Send inn',
    pl: 'Zatwierdź',
    pt: 'Submeter',
    ro: 'Trimite',
    ru: 'Отправить',
    sk: 'Odoslať',
    sl: 'Oddaj',
    sq: 'Paraqit',
    sv: 'Skicka',
    sw: 'Wasilisha',
    ta: 'சமர்ப்பி',
    te: 'సమర్పించండి',
    th: 'ส่ง',
    tl: 'Isumite',
    tr: 'Gönder',
    uk: 'Надіслати',
    ur: 'جمع کرائیں',
    vi: 'Gửi',
  },
  networkError: {
    zh: '网络错误',
    en: 'network error',
    ja: 'ネットワークエラー',
    af: 'netwerk fout',
    ar: 'خطأ في الشبكة',
    be: 'памылка сеткі',
    bg: 'мрежова грешка',
    bn: 'নেটওয়ার্ক ত্রুটি',
    ca: 'Error de xarxa',
    cs: 'chyba sítě',
    cy: 'gwall rhwydwaith',
    da: 'netværksfejl',
    de: 'Netzwerkfehler',
    el: 'σφάλμα δικτύου',
    eo: 'retoeraro',
    es: 'Error de red',
    et: 'Võrgu viga',
    fa: 'خطای شبکه',
    fi: 'Verkkovirhe',
    fr: 'Erreur réseau',
    ga: 'Earráid líonra',
    gl: 'Erro de rede',
    gu: 'નેટવર્ક ભૂલ',
    he: 'שגיאת רשת',
    hi: 'नेटवर्क त्रुटि',
    hr: 'Mrežna greška',
    ht: 'Erè rezo',
    hu: 'Hálózati hiba',
    id: 'Kesalahan jaringan',
    is: 'Netvilla',
    it: 'Errore di rete',
    ka: 'ქსელის შეცდომა',
    kn: 'ನೆಟ್ವರ್ಕ್ ದೋಷ',
    ko: '네트워크 오류',
    lt: 'Tinklo klaida',
    lv: 'Tīkla kļūda',
    mk: 'Мрежна грешка',
    mr: 'नेटवर्क त्रुटी',
    ms: 'Ralat rangkaian',
    mt: 'Żball tan-netwerk',
    nl: 'Netwerkfout',
    no: 'Nettverksfeil',
    pl: 'Błąd sieci',
    pt: 'Erro de rede',
    ro: 'Eroare de rețea',
    ru: 'Ошибка сети',
    sk: 'Chyba siete',
    sl: 'Napaka omrežja',
    sq: 'Gabim në rrjet',
    sv: 'nätverksfel',
    sw: 'hitilafu ya mtandao',
    ta: 'பிணைய பிழை',
    te: 'నెట్‌వర్క్ లోపం',
    th: 'ข้อผิดพลาดเครือข่าย',
    tl: 'error sa network',
    tr: 'ağ hatası',
    uk: 'мережева помилка',
    ur: 'نیٹ ورک کی خرابی',
    vi: 'lỗi mạng',
  },
  loginSuccess: {
    zh: '登录成功',
    en: 'Login Successful',
    ja: 'ログイン成功',
    af: 'Suksesvol aangemeld',
    ar: 'تم تسجيل الدخول بنجاح',
    be: 'паспяховы ўваход',
    bg: 'успешно влизане',
    bn: 'লগইন সফল',
    ca: 'Inici de sessió exitós',
    cs: 'Přihlášení úspěšné',
    cy: 'Mewngofnodi yn llwyddiannus',
    da: 'Logget ind succesfuldt',
    de: 'Erfolgreich angemeldet',
    el: 'Επιτυχής σύνδεση',
    eo: 'Sukcesa ensaluto',
    es: 'Inicio de sesión exitoso',
    et: 'Sisselogimine õnnestus',
    fa: 'ورود موفق',
    fi: 'Kirjautuminen onnistui',
    fr: 'Connexion réussie',
    ga: 'Logáil isteach rathúil',
    gl: 'Inicio de sesión exitoso',
    gu: 'સફળ લૉગિન',
    he: 'התחברות מוצלחת',
    hi: 'लॉग इन सफल',
    hr: 'Uspješna prijava',
    ht: 'Koneksyon reyisi',
    hu: 'Sikeres bejelentkezés',
    id: 'Berhasil masuk',
    is: 'Innskráning tókst',
    it: 'Accesso riuscito',
    ka: 'წარმატებული შესვლა',
    kn: 'ಲಾಗಿನ್ ಯಶಸ್ವಿ',
    ko: '로그인 성공',
    lt: 'Prisijungimas sėkmingas',
    lv: 'Pieteikšanās veiksmīga',
    mk: 'Успешна најава',
    mr: 'लॉगिन यशस्वी',
    ms: 'Log masuk berjaya',
    mt: "Idħol b'suċċess",
    nl: 'Succesvol ingelogd',
    no: 'Innlogging vellykket',
    pl: 'Logowanie powiodło się',
    pt: 'Login bem-sucedido',
    ro: 'Autentificare reușită',
    ru: 'Успешный вход',
    sk: 'Úspešné prihlásenie',
    sl: 'Uspešna prijava',
    sq: 'Hyrje e suksesshme',
    sv: 'inloggning lyckades',
    sw: 'kuingia kumefanikiwa',
    ta: 'உள்நுழைவு வெற்றி',
    te: 'లాగిన్ విజయవంతమైంది',
    th: 'เข้าสู่ระบบสำเร็จ',
    tl: 'matagumpay na pag-login',
    tr: 'başarılı giriş',
    uk: 'успішний вхід',
    ur: 'کامیاب لاگ ان',
    vi: 'đăng nhập thành công',
  },
  placeInputAccount: {
    zh: '请输入账号/邮箱/手机号',
    en: 'Please enter your account/email/phone number',
    ja: 'アカウント/メール/電話番号を入力してください',
    af: 'Voer jou rekening/e-pos/foonnommer in',
    ar: 'الرجاء إدخال الحساب/البريد الإلكتروني/رقم الهاتف',
    be: 'Увядзіце ўліковы запіс/электронную пошту/нумар тэлефона',
    bg: 'Моля, въведете акаунт/имейл/телефонен номер',
    bn: 'অ্যাকাউন্ট/ইমেল/ফোন নম্বর লিখুন',
    ca: 'Si us plau, introduïu el compte/correu electrònic/número de telèfon',
    cs: 'Zadejte prosím účet/e-mail/telefonní číslo',
    cy: 'Rhowch eich cyfrif/ebost/rhif ffôn',
    da: 'Indtast venligst konto/e-mail/telefonnummer',
    de: 'Bitte geben Sie Ihr Konto/E-Mail/Telefonnummer ein',
    el: 'Εισαγάγετε λογαριασμό/email/αριθμό τηλεφώνου',
    eo: 'Bonvolu enigi konton/retpoŝton/telefonnumeron',
    es: 'Por favor ingrese cuenta/correo electrónico/número de teléfono',
    et: 'Sisestage palun konto/e-post/telefoninumber',
    fa: 'لطفا حساب/ایمیل/شماره تلفن را وارد کنید',
    fi: 'Anna tilisi/sähköpostiosoitteesi/puhelinnumerosi',
    fr: 'Veuillez entrer votre compte/email/numéro de téléphone',
    ga: 'Cuir isteach do chuntas/ríomhphost/uimhir theileafóin',
    gl: 'Por favor, introduza conta/correo electrónico/número de teléfono',
    gu: 'કૃપા કરીને એકાઉન્ટ/ઇમેઇલ/ફોન નંબર દાખલ કરો',
    he: 'אנא הזן חשבון/אימייל/מספר טלפון',
    hi: 'कृपया खाता/ईमेल/फोन नंबर दर्ज करें',
    hr: 'Unesite račun/e-mail/telefonski broj',
    ht: 'Tanpri antre kont/imèl/nimewo telefòn',
    hu: 'Kérjük, adja meg fiókját/e-mail címét/telefonszámát',
    id: 'Silakan masukkan akun/email/nomor telepon',
    is: 'Vinsamlegast sláðu inn reikning/netfang/símanúmer',
    it: 'Per favore inserisci account/email/numero di telefono',
    ka: 'გთხოვთ, შეიყვანოთ ანგარიში/იმეილი/ტელეფონის ნომერი',
    kn: 'ದಯವಿಟ್ಟು ಖಾತೆ/ಇಮೇಲ್/ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    ko: '계정/이메일/전화번호를 입력해 주세요',
    lt: 'Įveskite paskyrą/el. paštą/telefono numerį',
    lv: 'Lūdzu, ievadiet kontu/e-pastu/telefona numuru',
    mk: 'Внесете сметка/е-пошта/телефонски број',
    mr: 'कृपया खाते/ईमेल/फोन नंबर प्रविष्ट करा',
    ms: 'Sila masukkan akaun/emel/nombor telefon',
    mt: 'Jekk jogħġbok daħħal kont/email/numru tat-telefon',
    nl: 'Voer account/e-mail/telefoonnummer in',
    no: 'Vennligst skriv inn konto/e-post/telefonnummer',
    pl: 'Proszę wprowadzić konto/e-mail/numer telefonu',
    pt: 'Por favor insira conta/email/número de telefone',
    ro: 'Vă rugăm să introduceți contul/e-mail-ul/numărul de telefon',
    ru: 'Пожалуйста, введите аккаунт/email/номер телефона',
    sk: 'Zadajte účet/e-mail/telefónne číslo',
    sl: 'Vnesite račun/e-pošto/telefonsko številko',
    sq: 'Ju lutemi shkruani llogarinë/emailin/numrin e telefonit',
    sv: 'Vänligen ange konto/e-post/telefonnummer',
    sw: 'Tafadhali ingiza akaunti/barua pepe/nambari ya simu',
    ta: 'கணக்கு/மின்னஞ்சல்/தொலைபேசி எண்ணை உள்ளிடவும்',
    te: 'దయచేసి ఖాతా/ఇమెయిల్/ఫోన్ నంబర్‌ని నమోదు చేయండి',
    th: 'กรุณาใส่บัญชี/อีเมล/หมายเลขโทรศัพท์',
    tl: 'Pakilagay ang account/email/numero ng telepono',
    tr: 'Lütfen hesap/e-posta/telefon numarası girin',
    uk: 'Будь ласка, введіть обліковий запис/електронну пошту/номер телефону',
    ur: 'براہ کرم اکاؤنٹ/ای میل/فون نمبر درج کریں',
    vi: 'Vui lòng nhập tài khoản/email/số điện thoại',
  },
  placeInputPassword: {
    zh: '请输入密码',
    en: 'Please enter password',
    ja: 'パスワードを入力してください',
    af: 'Voer wagwoord in',
    ar: 'الرجاء إدخال كلمة المرور',
    be: 'увядзіце пароль',
    bg: 'въведете парола',
    bn: 'পাসওয়ার্ড লিখুন',
    ca: 'Si us plau, introduïu la contrasenya',
    cs: 'Zadejte heslo',
    cy: 'Rhowch gyfrinair',
    da: 'Indtast adgangskode',
    de: 'Bitte Passwort eingeben',
    el: 'Παρακαλώ εισάγετε κωδικό πρόσβασης',
    eo: 'Bonvolu enigi pasvorton',
    es: 'Ingrese la contraseña',
    et: 'Sisestage parool',
    fa: 'لطفاً رمز عبور را وارد کنید',
    fi: 'Syötä salasana',
    fr: 'Veuillez entrer le mot de passe',
    ga: 'Cuir pasfhocal isteach le do thoil',
    gl: 'Introduce o contrasinal',
    gu: 'કૃપા કરીને પાસવર્ડ દાખલ કરો',
    he: 'אנא הזן סיסמה',
    hi: 'कृपया पासवर्ड दर्ज करें',
    hr: 'Molimo unesite lozinku',
    ht: 'Tanpri antre modpas',
    hu: 'Kérjük, adja meg a jelszót',
    id: 'Silakan masukkan kata sandi',
    is: 'Vinsamlegast sláðu inn lykilorð',
    it: 'Si prega di inserire la password',
    ka: 'გთხოვთ შეიყვანეთ პაროლი',
    kn: 'ದಯವಿಟ್ಟು ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    ko: '비밀번호를 입력하세요',
    lt: 'Įveskite slaptažodį',
    lv: 'Lūdzu, ievadiet paroli',
    mk: 'Внесете лозинка',
    mr: 'कृपया पासवर्ड प्रविष्ट करा',
    ms: 'Sila masukkan kata laluan',
    mt: 'Jekk jogħġbok daħħal il-password',
    nl: 'Voer alstublieft uw wachtwoord in',
    no: 'Vennligst skriv inn passord',
    pl: 'Proszę wprowadzić hasło',
    pt: 'Por favor, insira a senha',
    ro: 'Vă rugăm să introduceți parola',
    ru: 'Введите пароль',
    sk: 'Zadajte heslo',
    sl: 'Vnesite geslo',
    sq: 'Ju lutem, vendosni fjalëkalimin',
    sv: 'Ange lösenord',
    sw: 'Ingiza nenosiri',
    ta: 'கடவுச்சொல்லை உள்ளிடவும்',
    te: 'పాస్వర్డ్ ను నమోదు చేయండి',
    th: 'กรุณากรอกรหัสผ่าน',
    tl: 'Pakiusap, ilagay ang password',
    tr: 'Lütfen şifreyi girin',
    uk: 'Будь ласка, введіть пароль',
    ur: 'براہ کرم پاس ورڈ درج کریں',
    vi: 'Vui lòng nhập mật khẩu',
  },
  login: {
    zh: '登录',
    en: 'Login',
    ja: 'ログイン',
    af: 'Teken aan',
    ar: 'تسجيل الدخول',
    be: 'уваход',
    bg: 'влизане',
    bn: 'লগইন',
    ca: 'Inici de sessió',
    cs: 'Přihlášení',
    cy: 'Mewngofnodi',
    da: 'Log ind',
    de: 'Anmelden',
    el: 'Σύνδεση',
    eo: 'Ensaluti',
    es: 'Iniciar sesión',
    et: 'Logi sisse',
    fa: 'ورود',
    fi: 'Kirjaudu sisään',
    fr: 'Connexion',
    ga: 'Logáil isteach',
    gl: 'Iniciar sesión',
    gu: 'લૉગિન',
    he: 'התחבר',
    hi: 'लॉग इन',
    hr: 'Prijava',
    ht: 'Konekte',
    hu: 'Bejelentkezés',
    id: 'Masuk',
    is: 'Skrá inn',
    it: 'Accesso',
    ka: 'შესვლა',
    kn: 'ಲಾಗಿನ್',
    ko: '로그인',
    lt: 'Prisijungti',
    lv: 'Pieteikšanās',
    mk: 'Најава',
    mr: 'लॉगिन',
    ms: 'Log masuk',
    mt: 'Idħol',
    nl: 'Inloggen',
    no: 'Logg inn',
    pl: 'Zaloguj się',
    pt: 'Entrar',
    ro: 'Autentificare',
    ru: 'Войти',
    sk: 'Prihlásiť sa',
    sl: 'Prijava',
    sq: 'Hyrje',
    sv: 'logga in',
    sw: 'ingia',
    ta: 'உள்நுழை',
    te: 'లాగిన్',
    th: 'เข้าสู่ระบบ',
    tl: 'mag-login',
    tr: 'giriş yap',
    uk: 'увійти',
    ur: 'لاگ ان کریں',
    vi: 'đăng nhập',
  },
  notAccount: {
    zh: '没有账号',
    en: 'No account',
    ja: 'アカウントがありません',
    af: 'Geen rekening nie',
    ar: 'لا يوجد حساب',
    be: 'няма ўліковага запісу',
    bg: 'няма акаунт',
    bn: 'কোন অ্যাকাউন্ট নেই',
    ca: 'No tens compte',
    cs: 'Nemáte účet',
    cy: 'Does gennych chi ddim cyfrif',
    da: 'Ingen konto',
    de: 'Kein Konto',
    el: 'Δεν υπάρχει λογαριασμός',
    eo: 'Neniu konto',
    es: 'Sin cuenta',
    et: 'Kontot pole',
    fa: 'بدون حساب',
    fi: 'Ei tiliä',
    fr: 'Pas de compte',
    ga: 'Gan cuntas',
    gl: 'Sen conta',
    gu: 'કોઈ એકાઉન્ટ નથી',
    he: 'אין חשבון',
    hi: 'कोई खाता नहीं',
    hr: 'Nema računa',
    ht: 'Pa gen kont',
    hu: 'Nincs fiók',
    id: 'Tidak punya akun',
    is: 'Engin reikningur',
    it: 'Nessun account',
    ka: 'ანგარიში არ არის',
    kn: 'ಖಾತೆ ಇಲ್ಲ',
    ko: '계정 없음',
    lt: 'paskyros nėra',
    lv: 'Nav konta',
    mk: 'Нема сметка',
    mr: 'खाते नाही',
    ms: 'Tiada Akaun',
    mt: 'L-ebda Kont',
    nl: 'Geen Account',
    no: 'Ingen konto',
    pl: 'Brak konta',
    pt: 'Sem conta',
    ro: 'Fără cont',
    ru: 'Нет учетной записи',
    sk: 'Žiadny účet',
    sl: 'Ni računa',
    sq: 'Pa llogari',
    sv: 'Inget konto',
    sw: 'Hakuna akaunti',
    ta: 'கணக்கு இல்லை',
    te: 'ఖాతా లేదు',
    th: 'ไม่มีบัญชี',
    tl: 'Walang account',
    tr: 'Hesap yok',
    uk: 'Немає облікового запису',
    ur: 'کوئی اکاؤنٹ نہیں',
    vi: 'Không có tài khoản',
  },
  toRegister: {
    zh: '去注册',
    en: 'go to register',
    ja: '登録へ',
    af: 'gaan registreer',
    ar: 'اذهب للتسجيل',
    be: 'рэгістрацыя',
    bg: 'регистрация',
    bn: 'রেজিস্টার করতে যান',
    ca: 'anar a registrar',
    cs: 'jít k registraci',
    cy: 'mynd i gofrestru',
    da: 'gå til registrering',
    de: 'zur Registrierung gehen',
    el: 'πηγαίνετε στην εγγραφή',
    eo: 'iri al registriĝo',
    es: 'Ir a registrarse',
    et: 'Mine registreeruma',
    fa: 'برو به ثبت نام',
    fi: 'Mene rekisteröitymään',
    fr: "S'inscrire",
    ga: 'Clárú',
    gl: 'Rexistrarse',
    gu: 'રજિસ્ટર કરવા જાઓ',
    he: 'לעבור להרשמה',
    hi: 'पंजीकरण करने जाएं',
    hr: 'idi na registraciju',
    ht: 'ale enskri',
    hu: 'Regisztrációhoz',
    id: 'Ke pendaftaran',
    is: 'Til skráningar',
    it: 'Alla registrazione',
    ka: 'რეგისტრაციაზე გადასვლა',
    kn: 'ರಿಜಿಸ್ಟರ್‌ಗೆ ಹೋಗು',
    ko: '등록으로 이동',
    lt: 'eiti į registraciją',
    lv: 'Doties uz reģistrāciju',
    mk: 'Оди на регистрација',
    mr: 'नोंदणी करा',
    ms: 'Pergi ke pendaftaran',
    mt: 'Mur għar-reġistru',
    nl: 'Ga naar registratie',
    no: 'Registrer deg',
    pl: 'Zarejestruj się',
    pt: 'Registrar',
    ro: 'Înregistrează-te',
    ru: 'Перейти к регистрации',
    sk: 'Prejsť na registráciu',
    sl: 'Pojdi na registracijo',
    sq: 'Shko te regjistrimi',
    sv: 'Gå till registrering',
    sw: 'Nenda kusajili',
    ta: 'பதிவுசெய்ய செல்',
    te: 'నమోదు చేయడానికి వెళ్ళండి',
    th: 'ไปที่การลงทะเบียน',
    tl: 'Magparehistro',
    tr: 'Kayıt ol',
    uk: 'Зареєструватися',
    ur: 'رجسٹر کریں',
    vi: 'Đăng ký',
  },
  register: {
    zh: '注册',
    en: 'Register',
    ja: '登録',
    af: 'Registreer',
    ar: 'تسجيل',
    be: 'рэгістрацыя',
    bg: 'регистрация',
    bn: 'নিবন্ধন',
    ca: 'Registre',
    cs: 'Registrace',
    cy: 'Cofrestru',
    da: 'Registrer',
    de: 'Registrieren',
    el: 'Εγγραφή',
    eo: 'Registri',
    es: 'Registro',
    et: 'Registreerimine',
    fa: 'ثبت نام',
    fi: 'Rekisteröinti',
    fr: 'Inscription',
    ga: 'Clárú',
    gl: 'Rexistro',
    gu: 'રજિસ્ટ્રેશન',
    he: 'הרשמה',
    hi: 'पंजीकरण',
    hr: 'Registracija',
    ht: 'Enskripsyon',
    hu: 'Regisztráció',
    id: 'Daftar',
    is: 'Skráning',
    it: 'Registrazione',
    ka: 'რეგისტრაცია',
    kn: 'ನೋಂದಣಿ',
    ko: '등록',
    lt: 'registracija',
    lv: 'Reģistrēties',
    mk: 'Регистрација',
    mr: 'नोंदणी',
    ms: 'Daftar',
    mt: 'Reġistrazzjoni',
    nl: 'Registratie',
    no: 'Registrering',
    pl: 'Rejestracja',
    pt: 'Registro',
    ro: 'Înregistrare',
    ru: 'Регистрация',
    sk: 'Registrácia',
    sl: 'Registracija',
    sq: 'Regjistrim',
    sv: 'Registrera',
    sw: 'Jisajili',
    ta: 'பதிவு',
    te: 'నమోదు',
    th: 'สมัครสมาชิก',
    tl: 'Magrehistro',
    tr: 'Kayıt ol',
    uk: 'Реєстрація',
    ur: 'رجسٹر کریں',
    vi: 'Đăng ký',
  },
  createAccountError: {
    zh: '生成账号错误',
    en: 'Generate Account Error',
    ja: 'アカウントエラーを生成',
    af: 'Genereer rekeningfout',
    ar: 'خطأ في إنشاء الحساب',
    be: 'памылка генерацыі акаўнта',
    bg: 'грешка при генериране на акаунт',
    bn: 'অ্যাকাউন্ট তৈরিতে ত্রুটি',
    ca: 'Error en generar compte',
    cs: 'Chyba při generování účtu',
    cy: 'Gwall cynhyrchu cyfrif',
    da: 'Fejl ved generering af konto',
    de: 'Fehler beim Generieren des Kontos',
    el: 'Σφάλμα δημιουργίας λογαριασμού',
    eo: 'Eraro en generado de konto',
    es: 'Error al generar la cuenta',
    et: 'Konto genereerimise viga',
    fa: 'خطا در ایجاد حساب',
    fi: 'Tilin luonti epäonnistui',
    fr: 'Erreur de génération de compte',
    ga: 'Earráid ghiniúna cuntais',
    gl: 'Erro ao xerar a conta',
    gu: 'એકાઉન્ટ જનરેટ કરવામાં ભૂલ',
    he: 'שגיאה ביצירת חשבון',
    hi: 'खाता बनाने में त्रुटि',
    hr: 'Greška pri generiranju računa',
    ht: 'Erè nan kreye kont',
    hu: 'Fiók generálási hiba',
    id: 'Kesalahan menghasilkan akun',
    is: 'Villa við að búa til reikning',
    it: "Errore nella generazione dell'account",
    ka: 'ანგარიშის შექმნის შეცდომა',
    kn: 'ಖಾತೆ ರಚಿಸುವ ದೋಷ',
    ko: '계정 생성 오류',
    lt: 'Paskyros kūrimo klaida',
    lv: 'Konta izveides kļūda',
    mk: 'Грешка при создавање на сметка',
    mr: 'खाते तयार करण्यात त्रुटी',
    ms: 'Ralat penjanaan akaun',
    mt: 'Żball fil-ġenerazzjoni tal-kont',
    nl: 'Fout bij het genereren van een account',
    no: 'Generer kontofeil',
    pl: 'Błąd generowania konta',
    pt: 'Erro ao gerar conta',
    ro: 'Eroare la generarea contului',
    ru: 'Ошибка генерации аккаунта',
    sk: 'Chyba generovania účtu',
    sl: 'Napaka pri ustvarjanju računa',
    sq: 'Gabim gjenerimi i llogarisë',
    sv: 'fel vid generering av konto',
    sw: 'hitilafu ya kuzalisha akaunti',
    ta: 'கணக்கு உருவாக்க பிழை',
    te: 'ఖాతా సృష్టించే లోపం',
    th: 'ข้อผิดพลาดในการสร้างบัญชี',
    tl: 'Error sa Paggawa ng Account',
    tr: 'Hesap Oluşturma Hatası',
    uk: 'Помилка створення облікового запису',
    ur: 'اکاؤنٹ بنانے میں خرابی',
    vi: 'Lỗi tạo tài khoản',
  },
  registerError: {
    zh: '注册失败',
    en: 'Registration failed',
    ja: '登録失敗',
    af: 'Registrasie misluk',
    ar: 'فشل التسجيل',
    be: 'рэгістрацыя няўдалая',
    bg: 'регистрацията е неуспешна',
    bn: 'নিবন্ধন ব্যর্থ',
    ca: 'Error de registre',
    cs: 'Registrace selhala',
    cy: 'Methodd y cofrestriad',
    da: 'Registrering mislykkedes',
    de: 'Registrierung fehlgeschlagen',
    el: 'Η εγγραφή απέτυχε',
    eo: 'Registrado malsukcesis',
    es: 'Registro fallido',
    et: 'Registreerimine ebaõnnestus',
    fa: 'ثبت نام ناموفق',
    fi: 'Rekisteröinti epäonnistui',
    fr: "Échec de l'inscription",
    ga: 'Clárú teipthe',
    gl: 'Rexistro fallido',
    gu: 'રજિસ્ટ્રેશન નિષ્ફળ',
    he: 'הרשמה נכשלה',
    hi: 'पंजीकरण विफल',
    hr: 'Registracija neuspješna',
    ht: 'Enskripsyon echwe',
    hu: 'Sikertelen regisztráció',
    id: 'Pendaftaran gagal',
    is: 'Skráning mistókst',
    it: 'Registrazione fallita',
    ka: 'რეგისტრაცია ვერ მოხერხდა',
    kn: 'ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ',
    ko: '등록 실패',
    lt: 'registracija nepavyko',
    lv: 'Reģistrācija neizdevās',
    mk: 'Регистрацијата не успеа',
    mr: 'नोंदणी अयशस्वी',
    ms: 'Pendaftaran Gagal',
    mt: 'Reġistrazzjoni Falluta',
    nl: 'Registratie Mislukt',
    no: 'Registrering mislyktes',
    pl: 'Rejestracja nieudana',
    pt: 'Registro falhou',
    ro: 'Înregistrare eșuată',
    ru: 'Ошибка регистрации',
    sk: 'Neúspešná registrácia',
    sl: 'Neuspešna registracija',
    sq: 'Regjistrim i pasuksesshëm',
    sv: 'Registrering misslyckades',
    sw: 'Usajili umeshindwa',
    ta: 'பதிவு தோல்வி',
    te: 'నమోదు విఫలమైంది',
    th: 'การลงทะเบียนล้มเหลว',
    tl: 'Nabigo ang pagrehistro',
    tr: 'Kayıt başarısız',
    uk: 'Помилка реєстрації',
    ur: 'رجسٹریشن ناکام',
    vi: 'Đăng ký thất bại',
  },
  registerSuccess: {
    zh: '注册成功',
    en: 'Registration successful',
    ja: '登録成功',
    af: 'Registrasie suksesvol',
    ar: 'نجاح التسجيل',
    be: 'рэгістрацыя паспяховая',
    bg: 'регистрацията е успешна',
    bn: 'নিবন্ধন সফল',
    ca: 'Registre exitós',
    cs: 'Registrace úspěšná',
    cy: 'Cofrestriad llwyddiannus',
    da: 'Registrering lykkedes',
    de: 'Registrierung erfolgreich',
    el: 'Η εγγραφή ήταν επιτυχής',
    eo: 'Registrado sukcesis',
    es: 'Registro exitoso',
    et: 'Registreerimine õnnestus',
    fa: 'ثبت نام موفق',
    fi: 'Rekisteröinti onnistui',
    fr: 'Inscription réussie',
    ga: 'Clárú rathúil',
    gl: 'Rexistro exitoso',
    gu: 'રજિસ્ટ્રેશન સફળ',
    he: 'הרשמה הצליחה',
    hi: 'पंजीकरण सफल',
    hr: 'Registracija uspješna',
    ht: 'Enskripsyon reyisi',
    hu: 'Sikeres regisztráció',
    id: 'Pendaftaran berhasil',
    is: 'Skráning tókst',
    it: 'Registrazione riuscita',
    ka: 'რეგისტრაცია წარმატებით დასრულდა',
    kn: 'ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ',
    ko: '등록 성공',
    lt: 'registracija sėkminga',
    lv: 'Reģistrācija veiksmīga',
    mk: 'Регистрацијата успеа',
    mr: 'नोंदणी यशस्वी',
    ms: 'Pendaftaran Berjaya',
    mt: 'Reġistrazzjoni Suċċess',
    nl: 'Registratie Succesvol',
    no: 'Registrering vellykket',
    pl: 'Rejestracja udana',
    pt: 'Registro bem-sucedido',
    ro: 'Înregistrare reușită',
    ru: 'Успешная регистрация',
    sk: 'Úspešná registrácia',
    sl: 'Uspešna registracija',
    sq: 'Regjistrim i suksesshëm',
    sv: 'Registrering lyckades',
    sw: 'Usajili umefanikiwa',
    ta: 'பதிவு வெற்றி',
    te: 'నమోదు విజయవంతమైంది',
    th: 'การลงทะเบียนสำเร็จ',
    tl: 'Matagumpay ang pagrehistro',
    tr: 'Kayıt başarılı',
    uk: 'Успішна реєстрація',
    ur: 'رجسٹریشن کامیاب',
    vi: 'Đăng ký thành công',
  },
  hasAccount: {
    zh: '已有账号',
    en: 'Already Have Account',
    ja: 'アカウントあり',
    af: "Het reeds 'n rekening",
    ar: 'لديك حساب بالفعل',
    be: 'ужо ёсць уліковы запіс',
    bg: 'вече има акаунт',
    bn: 'অ্যাকাউন্ট আছে',
    ca: 'Compte existent',
    cs: 'Účet již existuje',
    cy: 'Mae cyfrif eisoes yn bodoli',
    da: 'Har allerede en konto',
    de: 'Bereits ein Konto vorhanden',
    el: 'Έχετε ήδη λογαριασμό',
    eo: 'Jam havas konton',
    es: 'Ya tienes una cuenta',
    et: 'Konto juba olemas',
    fa: 'حساب کاربری موجود است',
    fi: 'Tili on jo olemassa',
    fr: 'Compte existant',
    ga: 'Cuntas ann cheana',
    gl: 'Conta existente',
    gu: 'અસ્તિત્વમાં છે એકાઉન્ટ',
    he: 'יש כבר חשבון',
    hi: 'पहले से खाता है',
    hr: 'Već ima račun',
    ht: 'Deja gen kont',
    hu: 'Már van fiókja',
    id: 'Sudah memiliki akun',
    is: 'Á þegar reikning',
    it: 'Già ha un account',
    ka: 'უკვე არსებული ანგარიში',
    kn: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆ',
    ko: '이미 계정 있음',
    lt: 'jau turite paskyrą',
    lv: 'Ir konts',
    mk: 'Има сметка',
    mr: 'खाते आहे',
    ms: 'Mempunyai akaun',
    mt: 'Għandek Kont',
    nl: 'Heeft een account',
    no: 'har allerede konto',
    pl: 'posiada już konto',
    pt: 'já tem conta',
    ro: 'are deja cont',
    ru: 'Уже есть аккаунт',
    sk: 'Existujúci účet',
    sl: 'Obstoječi račun',
    sq: 'Llogari ekzistuese',
    sv: 'Har ett konto',
    sw: 'Tayari una akaunti',
    ta: 'ஏற்கனவே கணக்கு உள்ளது',
    te: 'ఖాతా ఉంది',
    th: 'มีบัญชีอยู่แล้ว',
    tl: 'Mayroon nang account',
    tr: 'Hesap var',
    uk: 'Обліковий запис існує',
    ur: 'اکاؤنٹ موجود ہے',
    vi: 'Đã có tài khoản',
  },
  toLogin: {
    zh: '去登录',
    en: 'go to login',
    ja: 'ログインへ',
    af: 'gaan aanmeld',
    ar: 'اذهب لتسجيل الدخول',
    be: 'уваход',
    bg: 'влизане',
    bn: 'লগইন করতে যান',
    ca: 'anar a iniciar sessió',
    cs: 'jít k přihlášení',
    cy: 'mynd i fewngofnodi',
    da: 'gå til login',
    de: 'zum Login gehen',
    el: 'πηγαίνετε στην σύνδεση',
    eo: 'iri al ensaluto',
    es: 'Ir a iniciar sesión',
    et: 'Mine sisse logima',
    fa: 'برو به ورود',
    fi: 'Mene kirjautumaan',
    fr: 'Se connecter',
    ga: 'Logáil isteach',
    gl: 'Iniciar sesión',
    gu: 'લોગિન કરવા જાઓ',
    he: 'לעבור להתחברות',
    hi: 'लॉगिन करने जाएं',
    hr: 'idi na prijavu',
    ht: 'ale konekte',
    hu: 'Bejelentkezéshez',
    id: 'Ke login',
    is: 'Til innskráningar',
    it: 'Al login',
    ka: 'შესვლაზე გადასვლა',
    kn: 'ಲಾಗಿನ್‌ಗೆ ಹೋಗು',
    ko: '로그인으로 이동',
    lt: 'eiti į prisijungimą',
    lv: 'Doties uz pierakstīšanos',
    mk: 'Оди на најава',
    mr: 'लॉगिन करा',
    ms: 'Pergi ke log masuk',
    mt: 'Mur għal-login',
    nl: 'Ga naar inloggen',
    no: 'Logg inn',
    pl: 'Zaloguj się',
    pt: 'Entrar',
    ro: 'Autentifică-te',
    ru: 'Перейти к входу',
    sk: 'Prejsť na prihlásenie',
    sl: 'Pojdi na prijavo',
    sq: 'Shko te kyçja',
    sv: 'Gå till inloggning',
    sw: 'Nenda kuingia',
    ta: 'உள்நுழைய செல்',
    te: 'లాగిన్ చేయడానికి వెళ్ళండి',
    th: 'ไปที่การเข้าสู่ระบบ',
    tl: 'Mag-login',
    tr: 'Giriş yap',
    uk: 'Увійти',
    ur: 'لاگ ان کریں',
    vi: 'Đăng nhập',
  },
  placeInputOldPassword: {
    zh: '请输入旧密码',
    en: 'Please enter old password',
    ja: '古いパスワードを入力してください',
    af: 'Voer ou wagwoord in',
    ar: 'الرجاء إدخال كلمة المرور القديمة',
    be: 'увядзіце стары пароль',
    bg: 'въведете стара парола',
    bn: 'পুরাতন পাসওয়ার্ড লিখুন',
    ca: 'Si us plau, introduïu la contrasenya antiga',
    cs: 'Zadejte staré heslo',
    cy: 'Rhowch gyfrinair hen',
    da: 'Indtast gammel adgangskode',
    de: 'Bitte altes Passwort eingeben',
    el: 'Παρακαλώ εισάγετε παλιό κωδικό πρόσβασης',
    eo: 'Bonvolu enigi malnovan pasvorton',
    es: 'Ingrese la contraseña anterior',
    et: 'Sisestage vana parool',
    fa: 'لطفاً رمز عبور قدیمی را وارد کنید',
    fi: 'Syötä vanha salasana',
    fr: "Veuillez entrer l'ancien mot de passe",
    ga: 'Cuir pasfhocal sean isteach le do thoil',
    gl: 'Introduce o contrasinal antigo',
    gu: 'કૃપા કરીને જૂનો પાસવર્ડ દાખલ કરો',
    he: 'אנא הזן סיסמה ישנה',
    hi: 'कृपया पुराना पासवर्ड दर्ज करें',
    hr: 'Molimo unesite staru lozinku',
    ht: 'Tanpri antre ansyen modpas',
    hu: 'Kérjük, adja meg a régi jelszót',
    id: 'Silakan masukkan kata sandi lama',
    is: 'Vinsamlegast sláðu inn gamalt lykilorð',
    it: 'Si prega di inserire la vecchia password',
    ka: 'გთხოვთ შეიყვანეთ ძველი პაროლი',
    kn: 'ದಯವಿಟ್ಟು ಹಳೆಯ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    ko: '이전 비밀번호를 입력하세요',
    lt: 'Įveskite seną slaptažodį',
    lv: 'Lūdzu, ievadiet veco paroli',
    mk: 'Внесете стара лозинка',
    mr: 'कृपया जुने पासवर्ड प्रविष्ट करा',
    ms: 'Sila masukkan kata laluan lama',
    mt: 'Jekk jogħġbok daħħal il-password l-qadima',
    nl: 'Voer alstublieft uw oude wachtwoord in',
    no: 'Vennligst skriv inn gammelt passord',
    pl: 'Proszę wprowadzić stare hasło',
    pt: 'Por favor, insira a senha antiga',
    ro: 'Vă rugăm să introduceți vechea parolă',
    ru: 'Введите старый пароль',
    sk: 'Zadajte staré heslo',
    sl: 'Vnesite staro geslo',
    sq: 'Ju lutem, vendosni fjalëkalimin e vjetër',
    sv: 'Ange gammalt lösenord',
    sw: 'Ingiza nenosiri la zamani',
    ta: 'பழைய கடவுச்சொல்லை உள்ளிடவும்',
    te: 'పాత పాస్వర్డ్ ను నమోదు చేయండి',
    th: 'กรุณากรอกรหัสผ่านเก่า',
    tl: 'Pakiusap, ilagay ang lumang password',
    tr: 'Lütfen eski şifreyi girin',
    uk: 'Будь ласка, введіть старий пароль',
    ur: 'براہ کرم پرانا پاس ورڈ درج کریں',
    vi: 'Vui lòng nhập mật khẩu cũ',
  },
  oldPasswordError: {
    zh: '旧密码错误',
    en: 'Old password error',
    ja: '古いパスワードエラー',
    af: 'Ou wagwoord foutief',
    ar: 'كلمة المرور القديمة خاطئة',
    be: 'Няправільны стары пароль',
    bg: 'Грешна стара парола',
    bn: 'পুরানো পাসওয়ার্ড ভুল',
    ca: 'Contrasenya antiga incorrecta',
    cs: 'Chybné staré heslo',
    cy: 'Hen gyfrinair anghywir',
    da: 'Gammelt kodeord er forkert',
    de: 'Altes Passwort ist falsch',
    el: 'Ο παλιός κωδικός πρόσβασης είναι λάθος',
    eo: 'Malnova pasvorto estas malĝusta',
    es: 'contraseña antigua incorrecta',
    et: 'vale vana parool',
    fa: 'رمز عبور قدیمی اشتباه است',
    fi: 'väärä vanha salasana',
    fr: 'ancien mot de passe incorrect',
    ga: 'seanfhocal faire mícheart',
    gl: 'contraseña antiga incorrecta',
    gu: 'જૂનો પાસવર્ડ ખોટો છે',
    he: 'סיסמה ישנה שגויה',
    hi: 'पुराना पासवर्ड गलत है',
    hr: 'Stara lozinka je pogrešna',
    ht: 'Ansyen modpas pa kòrèk',
    hu: 'Régi jelszó hibás',
    id: 'Password lama salah',
    is: 'Gamla lykilorðið rangt',
    it: 'Vecchia password errata',
    ka: 'ძველი პაროლი არასწორია',
    kn: 'ಹಳೆಯ ಪಾಸ್ವರ್ಡ್ ತಪ್ಪಾಗಿದೆ',
    ko: '이전 비밀번호 오류',
    lt: 'Senas slaptažodis neteisingas',
    lv: 'vecā parole nepareiza',
    mk: 'старата лозинка е погрешна',
    mr: 'जुने पासवर्ड चुकीचे आहे',
    ms: 'kata laluan lama salah',
    mt: 'password l-antika hija żbaljata',
    nl: 'oud wachtwoord incorrect',
    no: 'Gammelt passord feil',
    pl: 'Stare hasło nieprawidłowe',
    pt: 'Senha antiga incorreta',
    ro: 'Parolă veche incorectă',
    ru: 'старый пароль неверен',
    sk: 'staré heslo je nesprávne',
    sl: 'staro geslo je napačno',
    sq: 'fjalëkalimi i vjetër është i gabuar',
    sv: 'Fel gammalt lösenord',
    sw: 'Nenosiri la zamani si sahihi',
    ta: 'பழைய கடவுச்சொல் தவறு',
    te: 'పాత పాస్వర్డ్ తప్పు',
    th: 'รหัสผ่านเก่าผิด',
    tl: 'Maling Lumang Password',
    tr: 'Eski Şifre Yanlış',
    uk: 'Старий пароль невірний',
    ur: 'پرانا پاس ورڈ غلط ہے',
    vi: 'Mật khẩu cũ sai',
  },
  placeInputNewPassword: {
    zh: '请输入新密码',
    en: 'Please enter new password',
    ja: '新しいパスワードを入力してください',
    af: 'Voer nuwe wagwoord in',
    ar: 'الرجاء إدخال كلمة مرور جديدة',
    be: 'увядзіце новы пароль',
    bg: 'въведете нова парола',
    bn: 'নতুন পাসওয়ার্ড লিখুন',
    ca: 'Si us plau, introduïu la nova contrasenya',
    cs: 'Zadejte nové heslo',
    cy: 'Rhowch gyfrinair newydd',
    da: 'Indtast ny adgangskode',
    de: 'Bitte neues Passwort eingeben',
    el: 'Παρακαλώ εισάγετε νέο κωδικό πρόσβασης',
    eo: 'Bonvolu enigi novan pasvorton',
    es: 'Ingrese la nueva contraseña',
    et: 'Sisestage uus parool',
    fa: 'لطفاً رمز عبور جدید را وارد کنید',
    fi: 'Syötä uusi salasana',
    fr: 'Veuillez entrer un nouveau mot de passe',
    ga: 'Cuir pasfhocal nua isteach le do thoil',
    gl: 'Introduce un novo contrasinal',
    gu: 'કૃપા કરીને નવો પાસવર્ડ દાખલ કરો',
    he: 'אנא הזן סיסמה חדשה',
    hi: 'कृपया नया पासवर्ड दर्ज करें',
    hr: 'Molimo unesite novu lozinku',
    ht: 'Tanpri antre nouvo modpas',
    hu: 'Kérjük, adja meg az új jelszót',
    id: 'Silakan masukkan kata sandi baru',
    is: 'Vinsamlegast sláðu inn nýtt lykilorð',
    it: 'Si prega di inserire la nuova password',
    ka: 'გთხოვთ შეიყვანეთ ახალი პაროლი',
    kn: 'ದಯವಿಟ್ಟು ಹೊಸ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    ko: '새 비밀번호를 입력하세요',
    lt: 'Įveskite naują slaptažodį',
    lv: 'Lūdzu, ievadiet jauno paroli',
    mk: 'Внесете нова лозинка',
    mr: 'कृपया नवीन पासवर्ड प्रविष्ट करा',
    ms: 'Sila masukkan kata laluan baru',
    mt: 'Jekk jogħġbok daħħal password ġdida',
    nl: 'Voer alstublieft een nieuw wachtwoord in',
    no: 'Vennligst skriv inn nytt passord',
    pl: 'Proszę wprowadzić nowe hasło',
    pt: 'Por favor, insira a nova senha',
    ro: 'Vă rugăm să introduceți noua parolă',
    ru: 'Введите новый пароль',
    sk: 'Zadajte nové heslo',
    sl: 'Vnesite novo geslo',
    sq: 'Ju lutem, vendosni fjalëkalimin e ri',
    sv: 'Ange nytt lösenord',
    sw: 'Ingiza nenosiri jipya',
    ta: 'புதிய கடவுச்சொல்லை உள்ளிடவும்',
    te: 'కొత్త పాస్వర్డ్ ను నమోదు చేయండి',
    th: 'กรุณากรอกรหัสผ่านใหม่',
    tl: 'Pakiusap, ilagay ang bagong password',
    tr: 'Lütfen yeni şifreyi girin',
    uk: 'Будь ласка, введіть новий пароль',
    ur: 'براہ کرم نیا پاس ورڈ درج کریں',
    vi: 'Vui lòng nhập mật khẩu mới',
  },
  passwordMoreThanEight: {
    zh: '新密码至少八位',
    en: 'New password at least eight characters',
    ja: '新しいパスワードは少なくとも8文字',
    af: 'Nuwe wagwoord ten minste agt karakters',
    ar: 'كلمة المرور الجديدة يجب أن تكون على الأقل ثمانية أحرف',
    be: 'Новы пароль павінен быць не менш за восім знакаў',
    bg: 'Новата парола трябва да е поне осем знака',
    bn: 'নতুন পাসওয়ার্ড কমপক্ষে আট অক্ষর',
    ca: 'La nova contrasenya ha de tenir almenys vuit caràcters',
    cs: 'Nové heslo musí mít alespoň osm znaků',
    cy: 'Rhaid i gyfrinair newydd fod o leiaf wyth nod',
    da: 'Nyt kodeord skal være mindst otte tegn',
    de: 'Neues Passwort muss mindestens acht Zeichen lang sein',
    el: 'Ο νέος κωδικός πρόσβασης πρέπει να είναι τουλάχιστον οκτώ χαρακτήρες',
    eo: 'Nova pasvorto devas esti almenaŭ ok signoj',
    es: 'La nueva contraseña debe tener al menos ocho caracteres',
    et: 'Uus parool peab olema vähemalt kaheksa tähemärki pikk',
    fa: 'رمز عبور جدید باید حداقل هشت کاراکتر باشد',
    fi: 'Uuden salasanan on oltava vähintään kahdeksan merkkiä',
    fr: 'Le nouveau mot de passe doit comporter au moins huit caractères',
    ga: 'Caithfidh an pasfhocal nua a bheith ocht gcarachtar ar a laghad',
    gl: 'O novo contrasinal debe ter polo menos oito caracteres',
    gu: 'નવો પાસવર્ડ ઓછામાં ઓછા આઠ અક્ષરનો હોવો જોઈએ',
    he: 'סיסמה חדשה לפחות שמונה תווים',
    hi: 'नया पासवर्ड कम से कम आठ अक्षर',
    hr: 'Nova lozinka najmanje osam znakova',
    ht: 'Nouvo modpas omwen uit karaktè',
    hu: 'az új jelszónak legalább nyolc karakterből kell állnia',
    id: 'kata sandi baru minimal delapan karakter',
    is: 'nýtt lykilorð verður að vera að minnsta kosti átta stafir',
    it: 'la nuova password deve essere di almeno otto caratteri',
    ka: 'ახალი პაროლი უნდა იყოს მინიმუმ რვა სიმბოლო',
    kn: 'ಹೊಸ ಪಾಸ್ವರ್ಡ್ ಕನಿಷ್ಠ ಎಂಟು ಅಕ್ಷರಗಳು',
    ko: '새 비밀번호는 최소 8자 이상',
    lt: 'Naujas slaptažodis turi būti bent aštuonių simbolių',
    lv: 'Jaunajai parolei jābūt vismaz astoņām zīmēm',
    mk: 'Новата лозинка треба да биде најмалку осум знаци',
    mr: 'नवीन पासवर्ड किमान आठ वर्णांचा असावा',
    ms: 'Kata laluan baru sekurang-kurangnya lapan aksara',
    mt: 'Password ġdida tal-inqas tmien karattri',
    nl: 'Nieuw wachtwoord minstens acht tekens',
    no: 'Nytt passord minst åtte tegn',
    pl: 'Nowe hasło co najmniej osiem znaków',
    pt: 'Nova senha pelo menos oito caracteres',
    ro: 'Parolă nouă cel puțin opt caractere',
    ru: 'Новый пароль не менее восьми символов',
    sk: 'Nové heslo aspoň osem znakov',
    sl: 'Novo geslo vsaj osem znakov',
    sq: 'Fjalëkalimi i ri të paktën tetë shkronja',
    sv: 'Nytt lösenord måste vara minst åtta tecken',
    sw: 'Nenosiri jipya angalau herufi nane',
    ta: 'புதிய கடவுச்சொல் குறைந்தது எட்டு எழுத்துகள்',
    te: 'కొత్త పాస్వర్డ్ కనీసం ఎనిమిది అక్షరాలు',
    th: 'รหัสผ่านใหม่อย่างน้อยแปดตัวอักษร',
    tl: 'Hindi bababa sa walong karakter ang bagong password',
    tr: 'Yeni şifre en az sekiz karakter olmalıdır',
    uk: 'Новий пароль має бути не менше восьми символів',
    ur: 'نیا پاس ورڈ کم از کم آٹھ حروف کا ہونا چاہئے',
    vi: 'Mật khẩu mới ít nhất tám ký tự',
  },
  updatePasswordSuccess: {
    zh: '修改密码成功',
    en: 'Change Password Successful',
    ja: 'パスワード変更成功',
    af: 'wysig wagwoord suksesvol',
    ar: 'تم تعديل كلمة المرور بنجاح',
    be: 'паспяховая змена пароля',
    bg: 'успешна промяна на парола',
    bn: 'পাসওয়ার্ড পরিবর্তন সফল',
    ca: 'canvi de contrasenya exitós',
    cs: 'změna hesla úspěšná',
    cy: 'llwyddiant newid cyfrinair',
    da: 'skift adgangskode lykkedes',
    de: 'Ändern des Passworts erfolgreich',
    el: 'επιτυχία αλλαγής κωδικού πρόσβασης',
    eo: 'sukceso ŝanĝi pasvorton',
    es: 'Contraseña modificada con éxito',
    et: 'Parooli muutmine õnnestus',
    fa: 'تغییر رمز عبور موفقیت‌آمیز بود',
    fi: 'Salasanan vaihto onnistui',
    fr: 'Mot de passe modifié avec succès',
    ga: 'Pasfhocal modhnaithe go rathúil',
    gl: 'Contrasinal modificado correctamente',
    gu: 'પાસવર્ડ સફળતાપૂર્વક બદલાયો',
    he: 'הצלחת לשנות את הסיסמה',
    hi: 'पासवर्ड सफलतापूर्वक बदला गया',
    hr: 'Lozinka je uspješno promijenjena',
    ht: 'Modifye modpas la avèk siksè',
    hu: 'Jelszó módosítása sikeres',
    id: 'Berhasil mengubah kata sandi',
    is: 'Lykilorð breytt',
    it: 'Password modificata con successo',
    ka: 'პაროლის შეცვლა წარმატებით',
    kn: 'ಪಾಸ್ವರ್ಡ್ ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ',
    ko: '비밀번호 변경 성공',
    lt: 'Slaptažodis sėkmingai pakeistas',
    lv: 'Parole veiksmīgi mainīta',
    mk: 'Лозинката е успешно променета',
    mr: 'पासवर्ड यशस्वीरित्या बदलला',
    ms: 'Kata laluan berjaya diubah',
    mt: "Bidla l-password b'suċċess",
    nl: 'Wachtwoord succesvol gewijzigd',
    no: 'Endre passord vellykket',
    pl: 'Pomyślna zmiana hasła',
    pt: 'Senha alterada com sucesso',
    ro: 'Schimbare parolă reușită',
    ru: 'Пароль успешно изменен',
    sk: 'Heslo bolo úspešne zmenené',
    sl: 'Geslo uspešno spremenjeno',
    sq: 'Fjalëkalimi u ndryshua me sukses',
    sv: 'Lösenordet har ändrats',
    sw: 'Nenosiri limebadilishwa',
    ta: 'கடவுச்சொல் மாற்றப்பட்டது',
    te: 'పాస్వర్డ్ మార్చబడింది',
    th: 'เปลี่ยนรหัสผ่านสำเร็จ',
    tl: 'Matagumpay na pagbabago ng password',
    tr: 'Şifre değiştirme başarılı',
    uk: 'Пароль успішно змінено',
    ur: 'پاس ورڈ تبدیل کرنے میں کامیابی',
    vi: 'Thay đổi mật khẩu thành công',
  },
  updatePasswordFaile: {
    zh: '修改密码失败',
    en: 'Change Password Failed',
    ja: 'パスワード変更失敗',
    af: 'wysig wagwoord misluk',
    ar: 'فشل تعديل كلمة المرور',
    be: 'памылка змены пароля',
    bg: 'неуспешна промяна на парола',
    bn: 'পাসওয়ার্ড পরিবর্তন ব্যর্থ',
    ca: 'canvi de contrasenya fallit',
    cs: 'změna hesla selhala',
    cy: 'methodd newid cyfrinair',
    da: 'skift adgangskode mislykkedes',
    de: 'Ändern des Passworts fehlgeschlagen',
    el: 'αποτυχία αλλαγής κωδικού πρόσβασης',
    eo: 'malsukceso ŝanĝi pasvorton',
    es: 'fallo al cambiar contraseña',
    et: 'parooli muutmine ebaõnnestus',
    fa: 'خطا در تغییر رمز عبور',
    fi: 'salasanan vaihto epäonnistui',
    fr: 'échec de la modification du mot de passe',
    ga: 'teip ar mhodhnú pasfhocal',
    gl: 'fallo ao modificar contrasinal',
    gu: 'પાસવર્ડ સંપાદનમાં નિષ્ફળતા',
    he: 'שינוי סיסמה נכשל',
    hi: 'पासवर्ड संशोधित करने में विफल',
    hr: 'neuspješna izmjena lozinke',
    ht: 'modifikasyon modpas echwe',
    hu: 'jelszó módosítása sikertelen',
    id: 'gagal mengubah kata sandi',
    is: 'tókst ekki að breyta lykilorði',
    it: 'modifica password fallita',
    ka: 'პაროლის შეცვლა ვერ მოხერხდა',
    kn: 'ಪಾಸ್ವರ್ಡ್ ಬದಲಾಯಿಸಲು ವಿಫಲವಾಗಿದೆ',
    ko: '비밀번호 변경 실패',
    lt: 'slaptažodžio keitimas nepavyko',
    lv: 'Paroles maiņa neveiksmīga',
    mk: 'Неуспешно менување на лозинка',
    mr: 'पासवर्ड बदलणे अयशस्वी',
    ms: 'Gagal mengubah kata laluan',
    mt: 'tibdil tal-password falla',
    nl: 'wijzigen van wachtwoord mislukt',
    no: 'Endring av passord mislyktes',
    pl: 'Zmiana hasła nie powiodła się',
    pt: 'Falha ao modificar senha',
    ro: 'Modificarea parolei a eșuat',
    ru: 'Не удалось изменить пароль',
    sk: 'Zlyhala zmena hesla',
    sl: 'Sprememba gesla ni uspela',
    sq: 'Ndryshimi i fjalëkalimit dështoi',
    sv: 'Misslyckades med att ändra lösenord',
    sw: 'Imeshindwa kubadilisha nenosiri',
    ta: 'கடவுச்சொல்லை மாற்ற முடியவில்லை',
    te: 'పాస్వర్డ్ మార్చడంలో విఫలమైంది',
    th: 'การเปลี่ยนรหัสผ่านล้มเหลว',
    tl: 'Nabigong pagbabago ng password',
    tr: 'Şifre değiştirme başarısız',
    uk: 'Не вдалося змінити пароль',
    ur: 'پاس ورڈ تبدیل کرنے میں ناکامی',
    vi: 'Thay đổi mật khẩu thất bại',
  },
  oldPassword: {
    zh: '旧密码',
    en: 'Old password',
    ja: '古いパスワード',
    af: 'Ou wagwoord',
    ar: 'كلمة المرور القديمة',
    be: 'Стары пароль',
    bg: 'Стара парола',
    bn: 'পুরানো পাসওয়ার্ড',
    ca: 'Contrasenya antiga',
    cs: 'Staré heslo',
    cy: 'Hen gyfrinair',
    da: 'Gammelt kodeord',
    de: 'Altes Passwort',
    el: 'Παλιός κωδικός πρόσβασης',
    eo: 'Malnova pasvorto',
    es: 'contraseña antigua',
    et: 'vana parool',
    fa: 'رمز عبور قدیمی',
    fi: 'vanha salasana',
    fr: 'ancien mot de passe',
    ga: 'seanfhocal faire',
    gl: 'contraseña antiga',
    gu: 'જૂનો પાસવર્ડ',
    he: 'סיסמה ישנה',
    hi: 'पुराना पासवर्ड',
    hr: 'Stara lozinka',
    ht: 'Ansyen modpas',
    hu: 'Régi jelszó',
    id: 'Password lama',
    is: 'Gamla lykilorðið',
    it: 'Vecchia password',
    ka: 'ძველი პაროლი',
    kn: 'ಹಳೆಯ ಪಾಸ್ವರ್ಡ್',
    ko: '이전 비밀번호',
    lt: 'Senas slaptažodis',
    lv: 'vecā parole',
    mk: 'стара лозинка',
    mr: 'जुने पासवर्ड',
    ms: 'kata laluan lama',
    mt: 'password l-antika',
    nl: 'oud wachtwoord',
    no: 'Gammelt passord',
    pl: 'Stare hasło',
    pt: 'Senha antiga',
    ro: 'Parolă veche',
    ru: 'старый пароль',
    sk: 'staré heslo',
    sl: 'staro geslo',
    sq: 'fjalëkalimi i vjetër',
    sv: 'Gammalt lösenord',
    sw: 'Nenosiri la zamani',
    ta: 'பழைய கடவுச்சொல்',
    te: 'పాత పాస్వర్డ్',
    th: 'รหัสผ่านเก่า',
    tl: 'Lumang Password',
    tr: 'Eski Şifre',
    uk: 'Старий пароль',
    ur: 'پرانا پاس ورڈ',
    vi: 'Mật khẩu cũ',
  },
  newPassword: {
    zh: '新密码',
    en: 'New password',
    ja: '新しいパスワード',
    af: 'Nuwe wagwoord',
    ar: 'كلمة مرور جديدة',
    be: 'Новы пароль',
    bg: 'Нова парола',
    bn: 'নতুন পাসওয়ার্ড',
    ca: 'Nova contrasenya',
    cs: 'Nové heslo',
    cy: 'Cyfrinair newydd',
    da: 'Nyt kodeord',
    de: 'Neues Passwort',
    el: 'Νέος κωδικός πρόσβασης',
    eo: 'Nova pasvorto',
    es: 'Nueva contraseña',
    et: 'Uus parool',
    fa: 'رمز عبور جدید',
    fi: 'Uusi salasana',
    fr: 'Nouveau mot de passe',
    ga: 'Pasfhocal nua',
    gl: 'Novo contrasinal',
    gu: 'નવો પાસવર્ડ',
    he: 'סיסמה חדשה',
    hi: 'नया पासवर्ड',
    hr: 'Nova lozinka',
    ht: 'Nouvo modpas',
    hu: 'új jelszó',
    id: 'kata sandi baru',
    is: 'nýtt lykilorð',
    it: 'nuova password',
    ka: 'ახალი პაროლი',
    kn: 'ಹೊಸ ಪಾಸ್ವರ್ಡ್',
    ko: '새 비밀번호',
    lt: 'Naujas slaptažodis',
    lv: 'Jaunā parole',
    mk: 'Нова лозинка',
    mr: 'नवीन पासवर्ड',
    ms: 'Kata laluan baru',
    mt: 'Password ġdida',
    nl: 'Nieuw wachtwoord',
    no: 'Nytt passord',
    pl: 'Nowe hasło',
    pt: 'Nova senha',
    ro: 'Parolă nouă',
    ru: 'Новый пароль',
    sk: 'Nové heslo',
    sl: 'Novo geslo',
    sq: 'Fjalëkalimi i ri',
    sv: 'Nytt lösenord',
    sw: 'Nenosiri jipya',
    ta: 'புதிய கடவுச்சொல்',
    te: 'కొత్త పాస్వర్డ్',
    th: 'รหัสผ่านใหม่',
    tl: 'Bagong Password',
    tr: 'Yeni Şifre',
    uk: 'Новий пароль',
    ur: 'نیا پاس ورڈ',
    vi: 'Mật khẩu mới',
  },
  updateInfoSuccess: {
    zh: '修改信息成功',
    en: 'Modify Information Successful',
    ja: '情報変更成功',
    af: 'wysig inligting suksesvol',
    ar: 'تم تعديل المعلومات بنجاح',
    be: 'паспяховая змена інфармацыі',
    bg: 'успешна промяна на информация',
    bn: 'তথ্য সংশোধন সফল',
    ca: "modificació d'informació exitosa",
    cs: 'úprava informací úspěšná',
    cy: 'llwyddiant golygu gwybodaeth',
    da: 'redigering af information lykkedes',
    de: 'Bearbeiten der Information erfolgreich',
    el: 'επιτυχία επεξεργασίας πληροφοριών',
    eo: 'sukceso redakti informon',
    es: 'éxito al modificar información',
    et: 'teabe muutmine õnnestus',
    fa: 'موفقیت در ویرایش اطلاعات',
    fi: 'tietojen muokkaus onnistui',
    fr: "succès de la modification de l'information",
    ga: 'rath ar mhodhnú faisnéise',
    gl: 'éxito ao modificar información',
    gu: 'માહિતી સંપાદનમાં સફળતા',
    he: 'שינוי מידע הצליח',
    hi: 'जानकारी संशोधित करने में सफल',
    hr: 'uspješna izmjena informacija',
    ht: 'modifikasyon enfòmasyon reyisi',
    hu: 'információ módosítása sikeres',
    id: 'berhasil mengubah informasi',
    is: 'tókst að breyta upplýsingum',
    it: 'modifica informazioni riuscita',
    ka: 'ინფორმაციის რედაქტირება წარმატებული',
    kn: 'ಮಾಹಿತಿ ಸಂಪಾದಿಸುವುದು ಯಶಸ್ವಿ',
    ko: '정보 수정 성공',
    lt: 'informacijos redagavimas sėkmingas',
    lv: 'Informācijas labošana veiksmīga',
    mk: 'Успешно менување на информации',
    mr: 'माहिती सुधारणे यशस्वी',
    ms: 'Berjaya mengubah maklumat',
    mt: "tibdil tal-informazzjoni b'suċċess",
    nl: 'wijzigen van informatie geslaagd',
    no: 'Endring av informasjon vellykket',
    pl: 'Zmiana informacji powiodła się',
    pt: 'Informação modificada com sucesso',
    ro: 'Modificarea informației a reușit',
    ru: 'Информация успешно изменена',
    sk: 'Informácia úspešne zmenená',
    sl: 'Informacija uspešno spremenjena',
    sq: 'Informacioni u ndryshua me sukses',
    sv: 'Informationen har ändrats',
    sw: 'Taarifa imebadilishwa',
    ta: 'தகவல் மாற்றப்பட்டது',
    te: 'సమాచారం మార్చబడింది',
    th: 'แก้ไขข้อมูลสำเร็จ',
    tl: 'Matagumpay na pagbabago ng impormasyon',
    tr: 'Bilgi değiştirme başarılı',
    uk: 'Інформацію успішно змінено',
    ur: 'معلومات کی تبدیلی کامیاب',
    vi: 'Thay đổi thông tin thành công',
  },
  updateInfoError: {
    zh: '修改信息失败',
    en: 'Modify Information Failed',
    ja: '情報変更失敗',
    af: 'wysig inligting misluk',
    ar: 'فشل تعديل المعلومات',
    be: 'памылка змены інфармацыі',
    bg: 'неуспешна промяна на информация',
    bn: 'তথ্য সংশোধন ব্যর্থ',
    ca: "modificació d'informació fallida",
    cs: 'úprava informací selhala',
    cy: 'methodd golygu gwybodaeth',
    da: 'redigering af information mislykkedes',
    de: 'Bearbeiten der Information fehlgeschlagen',
    el: 'αποτυχία επεξεργασίας πληροφοριών',
    eo: 'malsukceso redakti informon',
    es: 'fallo al modificar información',
    et: 'teabe muutmine ebaõnnestus',
    fa: 'خطا در ویرایش اطلاعات',
    fi: 'tietojen muokkaus epäonnistui',
    fr: "échec de la modification de l'information",
    ga: 'teip ar mhodhnú faisnéise',
    gl: 'fallo ao modificar información',
    gu: 'માહિતી સંપાદનમાં નિષ્ફળતા',
    he: 'שינוי מידע נכשל',
    hi: 'जानकारी संशोधित करने में विफल',
    hr: 'neuspješna izmjena informacija',
    ht: 'modifikasyon enfòmasyon echwe',
    hu: 'információ módosítása sikertelen',
    id: 'gagal mengubah informasi',
    is: 'tókst ekki að breyta upplýsingum',
    it: 'modifica informazioni fallita',
    ka: 'ინფორმაციის რედაქტირება ვერ მოხერხდა',
    kn: 'ಮಾಹಿತಿ ಸಂಪಾದಿಸಲು ವಿಫಲವಾಗಿದೆ',
    ko: '정보 수정 실패',
    lt: 'informacijos redagavimas nepavyko',
    lv: 'Informācijas labošana neveiksmīga',
    mk: 'Неуспешно менување на информации',
    mr: 'माहिती सुधारणे अयशस्वी',
    ms: 'Gagal mengubah maklumat',
    mt: 'tibdil tal-informazzjoni falla',
    nl: 'wijzigen van informatie mislukt',
    no: 'Endring av informasjon mislyktes',
    pl: 'Zmiana informacji nie powiodła się',
    pt: 'Falha ao modificar informação',
    ro: 'Modificarea informației a eșuat',
    ru: 'Не удалось изменить информацию',
    sk: 'Zlyhala zmena informácie',
    sl: 'Sprememba informacije ni uspela',
    sq: 'Ndryshimi i informacionit dështoi',
    sv: 'Misslyckades med att ändra information',
    sw: 'Imeshindwa kubadilisha taarifa',
    ta: 'தகவலை மாற்ற முடியவில்லை',
    te: 'సమాచారాన్ని మార్చడంలో విఫలమైంది',
    th: 'การแก้ไขข้อมูลล้มเหลว',
    tl: 'Nabigong pagbabago ng impormasyon',
    tr: 'Bilgi değiştirme başarısız',
    uk: 'Не вдалося змінити інформацію',
    ur: 'معلومات کی تبدیلی ناکام',
    vi: 'Thay đổi thông tin thất bại',
  },
  palceLogin: {
    zh: '请先登录',
    en: 'Please log in first',
    ja: 'まずログインしてください',
    af: 'Teken eers aan',
    ar: 'الرجاء تسجيل الدخول أولاً',
    be: 'увайдзіце спачатку',
    bg: 'влезте първо',
    bn: 'প্রথমে লগইন করুন',
    ca: 'Si us plau, inicieu sessió primer',
    cs: 'Nejprve se přihlaste',
    cy: 'Mewngofnodi yn gyntaf',
    da: 'Log ind først',
    de: 'Bitte zuerst anmelden',
    el: 'Παρακαλώ συνδεθείτε πρώτα',
    eo: 'Bonvolu unue ensaluti',
    es: 'Inicie sesión primero',
    et: 'Logige esmalt sisse',
    fa: 'لطفاً ابتدا وارد شوید',
    fi: 'Kirjaudu ensin sisään',
    fr: "Veuillez d'abord vous connecter",
    ga: 'Logáil isteach ar dtús le do thoil',
    gl: 'Inicia sesión primeiro',
    gu: 'પહેલા લૉગિન કરો',
    he: 'אנא התחבר תחילה',
    hi: 'कृपया पहले लॉगिन करें',
    hr: 'Molimo prvo prijavite se',
    ht: 'Tanpri konekte anvan',
    hu: 'Kérjük, először jelentkezzen be',
    id: 'Harap masuk terlebih dahulu',
    is: 'Vinsamlegast skráðu þig inn fyrst',
    it: 'Si prega di accedere prima',
    ka: 'გთხოვთ ჯერ შეხვიდეთ სისტემაში',
    kn: 'ದಯವಿಟ್ಟು ಮೊದಲು ಲಾಗಿನ್ ಮಾಡಿ',
    ko: '먼저 로그인하세요',
    lt: 'Pirmiausia prisijunkite',
    lv: 'Lūdzu, vispirms pieslēdzieties',
    mk: 'Ве молиме, прво најавете се',
    mr: 'कृपया प्रथम लॉगिन करा',
    ms: 'Sila log masuk dahulu',
    mt: 'Idħol l-ewwel',
    nl: 'Log eerst in',
    no: 'Vennligst logg inn først',
    pl: 'Proszę się najpierw zalogować',
    pt: 'Por favor, faça login primeiro',
    ro: 'Vă rugăm să vă autentificați mai întâi',
    ru: 'Пожалуйста, войдите сначала',
    sk: 'Prosím, prihláste sa najprv',
    sl: 'Prosimo, najprej se prijavite',
    sq: 'Ju lutemi, identifikohu së pari',
    sv: 'Var god logga in först',
    sw: 'Tafadhali ingia kwanza',
    ta: 'முதலில் உள்நுழையவும்',
    te: 'మొదట లాగిన్ అవ్వండి',
    th: 'กรุณาเข้าสู่ระบบก่อน',
    tl: 'mangyaring mag-login muna',
    tr: 'lütfen önce giriş yapın',
    uk: 'будь ласка, спочатку увійдіть',
    ur: 'براہ کرم پہلے لاگ ان کریں',
    vi: 'vui lòng đăng nhập trước',
  },
  pickLang: {
    zh: '选择语言',
    en: 'Select Language',
    ja: '言語を選択',
    af: 'Kies Taal',
    ar: 'اختر اللغة',
    be: 'Выберыце мову',
    bg: 'Изберете език',
    bn: 'ভাষা নির্বাচন করুন',
    ca: 'Selecciona idioma',
    cs: 'Vyberte jazyk',
    cy: 'Dewiswch Iaith',
    da: 'Vælg sprog',
    de: 'Sprache auswählen',
    el: 'Επιλέξτε γλώσσα',
    eo: 'Elektu lingvon',
    es: 'Seleccionar idioma',
    et: 'Vali keel',
    fa: 'انتخاب زبان',
    fi: 'Valitse kieli',
    fr: 'Sélectionner la langue',
    ga: 'Roghnaigh teanga',
    gl: 'Seleccionar o idioma',
    gu: 'ભાષા પસંદ કરો',
    he: 'בחר שפה',
    hi: 'भाषा चुनें',
    hr: 'odaberi jezik',
    ht: 'chwazi lang',
    hu: 'Nyelv kiválasztása',
    id: 'Pilih bahasa',
    is: 'Veldu tungumál',
    it: 'Seleziona lingua',
    ka: 'ენის არჩევა',
    kn: 'ಭಾಷೆ ಆಯ್ಕೆ',
    ko: '언어 선택',
    lt: 'pasirinkti kalbą',
    lv: 'Izvēlēties valodu',
    mk: 'Изберете јазик',
    mr: 'भाषा निवडा',
    ms: 'Pilih bahasa',
    mt: 'Agħżel lingwa',
    nl: 'Selecteer taal',
    no: 'Velg språk',
    pl: 'Wybierz język',
    pt: 'Selecione o idioma',
    ro: 'Selectați limba',
    ru: 'Выберите язык',
    sk: 'Vyberte jazyk',
    sl: 'Izberite jezik',
    sq: 'Zgjidhni gjuhën',
    sv: 'Välj språk',
    sw: 'Chagua lugha',
    ta: 'மொழியைத் தேர்ந்தெடு',
    te: 'భాషను ఎంచుకోండి',
    th: 'เลือกภาษา',
    tl: 'Pumili ng wika',
    tr: 'Dil seç',
    uk: 'Виберіть мову',
    ur: 'زبان منتخب کریں',
    vi: 'Chọn ngôn ngữ',
  },
  baseInfo: {
    zh: '基本信息',
    en: 'basic information',
    ja: '基本情報',
    af: 'basiese inligting',
    ar: 'المعلومات الأساسية',
    be: 'асноўная інфармацыя',
    bg: 'основна информация',
    bn: 'মৌলিক তথ্য',
    ca: 'informació bàsica',
    cs: 'základní informace',
    cy: 'gwybodaeth sylfaenol',
    da: 'grundlæggende information',
    de: 'grundlegende Informationen',
    el: 'βασικές πληροφορίες',
    eo: 'baza informo',
    es: 'información básica',
    et: 'põhiinfo',
    fa: 'اطلاعات پایه',
    fi: 'perustiedot',
    fr: 'informations de base',
    ga: 'eolas bunúsach',
    gl: 'información básica',
    gu: 'મૂળભૂત માહિતી',
    he: 'מידע בסיסי',
    hi: 'मूल जानकारी',
    hr: 'osnovne informacije',
    ht: 'enfòmasyon debaz',
    hu: 'alapvető információk',
    id: 'informasi dasar',
    is: 'grunnupplýsingar',
    it: 'informazioni di base',
    ka: 'ძირითადი ინფორმაცია',
    kn: 'ಮೂಲ ಮಾಹಿತಿ',
    ko: '기본 정보',
    lt: 'pagrindinė informacija',
    lv: 'pamatinformācija',
    mk: 'основни информации',
    mr: 'मूलभूत माहिती',
    ms: 'maklumat asas',
    mt: 'informazzjoni bażika',
    nl: 'basisinformatie',
    no: 'Grunnleggende informasjon',
    pl: 'Podstawowe informacje',
    pt: 'Informações básicas',
    ro: 'Informații de bază',
    ru: 'Основная информация',
    sk: 'Základné informácie',
    sl: 'Osnovne informacije',
    sq: 'Informacioni bazë',
    sv: 'Grundläggande information',
    sw: 'Maelezo ya msingi',
    ta: 'அடிப்படை தகவல்',
    te: 'ప్రాథమిక సమాచారం',
    th: 'ข้อมูลพื้นฐาน',
    tl: 'Pangunahing Impormasyon',
    tr: 'Temel Bilgiler',
    uk: 'Основна інформація',
    ur: 'بنیادی معلومات',
    vi: 'Thông tin cơ bản',
  },
  updatePassword: {
    zh: '修改密码',
    en: 'Change Password',
    ja: 'パスワードを変更',
    af: 'wysig wagwoord',
    ar: 'تعديل كلمة المرور',
    be: 'змяніць пароль',
    bg: 'промяна на парола',
    bn: 'পাসওয়ার্ড পরিবর্তন',
    ca: 'canviar contrasenya',
    cs: 'změna hesla',
    cy: 'newid cyfrinair',
    da: 'skift adgangskode',
    de: 'Passwort ändern',
    el: 'αλλαγή κωδικού πρόσβασης',
    eo: 'ŝanĝi pasvorton',
    es: 'cambiar contraseña',
    et: 'muuda parooli',
    fa: 'تغییر رمز عبور',
    fi: 'vaihda salasana',
    fr: 'modifier le mot de passe',
    ga: 'pasfhocal a mhodhnú',
    gl: 'modificar contrasinal',
    gu: 'પાસવર્ડ સંપાદિત કરો',
    he: 'לשנות סיסמה',
    hi: 'पासवर्ड संशोधित करें',
    hr: 'izmijeni lozinku',
    ht: 'modifye modpas',
    hu: 'jelszó módosítása',
    id: 'mengubah kata sandi',
    is: 'breyta lykilorði',
    it: 'modifica password',
    ka: 'პაროლის შეცვლა',
    kn: 'ಪಾಸ್ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    ko: '비밀번호 변경',
    lt: 'slaptažodžio keitimas',
    lv: 'Mainīt paroli',
    mk: 'Измени лозинка',
    mr: 'पासवर्ड बदला',
    ms: 'Ubah kata laluan',
    mt: 'ibdel il-password',
    nl: 'wachtwoord wijzigen',
    no: 'Endre passord',
    pl: 'Zmień hasło',
    pt: 'Modificar senha',
    ro: 'Modificare parolă',
    ru: 'Изменить пароль',
    sk: 'Zmeniť heslo',
    sl: 'Spremeni geslo',
    sq: 'Ndrysho fjalëkalimin',
    sv: 'Ändra lösenord',
    sw: 'Badilisha nenosiri',
    ta: 'கடவுச்சொல்லை மாற்று',
    te: 'పాస్వర్డ్ మార్చండి',
    th: 'เปลี่ยนรหัสผ่าน',
    tl: 'Pagbabago ng password',
    tr: 'Şifre değiştirme',
    uk: 'Зміна пароля',
    ur: 'پاس ورڈ تبدیل کریں',
    vi: 'Thay đổi mật khẩu',
  },
  logout: {
    zh: '退出登录',
    en: 'Log out',
    ja: 'ログアウト',
    af: 'Teken uit',
    ar: 'تسجيل الخروج',
    be: 'выйсці з сістэмы',
    bg: 'изход от системата',
    bn: 'লগআউট',
    ca: 'Tanca la sessió',
    cs: 'Odhlásit se',
    cy: 'Allgofnodi',
    da: 'Log ud',
    de: 'Abmelden',
    el: 'Αποσύνδεση',
    eo: 'Elsaluti',
    es: 'Cerrar sesión',
    et: 'Logi välja',
    fa: 'خروج از حساب',
    fi: 'Kirjaudu ulos',
    fr: 'Déconnexion',
    ga: 'Logáil amach',
    gl: 'Desconectar',
    gu: 'લૉગ આઉટ',
    he: 'יציאה מהחשבון',
    hi: 'लॉगआउट',
    hr: 'odjava',
    ht: 'dekoneksyon',
    hu: 'Kijelentkezés',
    id: 'Keluar',
    is: 'Útskráning',
    it: 'Disconnetti',
    ka: 'გამოსვლა',
    kn: 'ಲಾಗ್ ಔಟ್',
    ko: '로그아웃',
    lt: 'atsijungimas',
    lv: 'Izrakstīšanās',
    mk: 'Одјава',
    mr: 'लॉगआउट',
    ms: 'Log Keluar',
    mt: 'oħroġ',
    nl: 'uitloggen',
    no: 'Logg ut',
    pl: 'Wyloguj się',
    pt: 'Sair',
    ro: 'Deconectare',
    ru: 'Выйти из системы',
    sk: 'Odhlásiť sa',
    sl: 'Odjava',
    sq: 'Dilni',
    sv: 'logga ut',
    sw: 'ondoka',
    ta: 'வெளியேறு',
    te: 'లాగ్అవుట్',
    th: 'ออกจากระบบ',
    tl: 'Mag-log Out',
    tr: 'Çıkış Yap',
    uk: 'Вийти з системи',
    ur: 'لاگ آؤٹ کریں',
    vi: 'Đăng xuất',
  },
  notLogin: {
    zh: '未登录',
    en: 'Not logged in',
    ja: '未ログイン',
    af: 'Nie aangemeld',
    ar: 'غير مسجل الدخول',
    be: 'не ўвайшлі',
    bg: 'не сте влезли',
    bn: 'লগইন করা হয়নি',
    ca: 'No iniciat sessió',
    cs: 'Nepřihlášen',
    cy: 'Mewngofnodi',
    da: 'Ikke logget ind',
    de: 'Nicht angemeldet',
    el: 'Δεν έχετε συνδεθεί',
    eo: 'Ne ensalutita',
    es: 'no conectado',
    et: 'sisse logimata',
    fa: 'وارد نشده',
    fi: 'ei kirjautunut',
    fr: 'non connecté',
    ga: 'gan logáil isteach',
    gl: 'non conectado',
    gu: 'લોગઇન નથી',
    he: 'לא מחובר',
    hi: 'लॉगिन नहीं किया',
    hr: 'Nije prijavljen',
    ht: 'Pa konekte',
    hu: 'Nincs bejelentkezve',
    id: 'Belum login',
    is: 'Ekki skráður inn',
    it: 'Non connesso',
    ka: 'არ არის შესული',
    kn: 'ಲಾಗಿನ್ ಆಗಿಲ್ಲ',
    ko: '로그인되지 않음',
    lt: 'Neprisijungęs',
    lv: 'Nav pieteicies',
    mk: 'Не е најавен',
    mr: 'प्रवेश केलेला नाही',
    ms: 'Tidak log masuk',
    mt: 'Mhux illogjat',
    nl: 'Niet ingelogd',
    no: 'Ikke innlogget',
    pl: 'Nie zalogowano',
    pt: 'Não logado',
    ro: 'Neautentificat',
    ru: 'Не авторизован',
    sk: 'Neprihlásený',
    sl: 'Neprijavljen',
    sq: 'I paidentifikuar',
    sv: 'Inte inloggad',
    sw: 'Haijaingia',
    ta: 'உள்நுழையவில்லை',
    te: 'లాగిన్ కాలేదు',
    th: 'ไม่ได้ล็อกอิน',
    tl: 'Hindi naka-login',
    tr: 'Giriş yapılmamış',
    uk: 'Не ввійшли в систему',
    ur: 'لاگ ان نہیں کیا',
    vi: 'Chưa đăng nhập',
  },
}
